### ISSUE TITLE
rtmp直播流延迟太大怎么解

### ISSUE THREAD

**Issue by FrankLove** [tsingsee/EasyPlayer-RTMP-Android#2]
rtmp直播流延迟太大怎么解决呢

**Comment by milkywayriver** [comment]
不应该延迟大的.先自查下原因吧,网络情况等因素.可以用第三方播放器对比下.

**Comment by FrankLove** [comment]
@milkywayriver 相同环境下用第三方编译的ijkplayer延迟比EasyPlayer要好很多，如果在连续直播的情况下EasyPlayer延迟会越来越大，但是通过修改ijkplayer播放参数，在连续播放一个小时的情况下可以保持1-2秒的延迟，但是EasyPlayer应该不行

**Comment by leo-09** [comment]
切换成硬解码 测试下

**Comment by leo-09** [comment]
最新版本中已修正，在局域网中测试延迟200ms左右
